### ISSUE TITLE
Problem with installation (invoice.html (Errno::ENOENT))

### ISSUE THREAD

**Issue by SukiCZ** [jdennes/invoices#6]
Hi :wave: ,
I have an issue installing/running this repository. I followed the guideline, installed the packages (globally I think) but when I try to run (step 4):
`./script/invoice`
It ends with following error
```
Configuration file: /home/suki/projects/invoices/_config.yml
            Source: /home/suki/projects/invoices
       Destination: /home/suki/projects/invoices/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.019 seconds.
 Auto-regeneration: disabled. Use --watch to enable.
Traceback (most recent call last):
	1: from ./script/invoice:58:in `<main>'
./script/invoice:58:in `read': No such file or directory @ rb_sysopen - /home/suki/projects/invoices/_site/2018/10/31/invoice.html (Errno::ENOENT)

```
I think `invoice.html` is missing but can not figure out where to get it from.
Any help would be appreciated - I hate invoicing in Excel.
Thanks :heart:

**Comment by jdennes** [comment]
Hey there, I don't use this personally any more, but I think I found the problem.

In a fresh clone and after following the setup instructions, it appears that Jekyll now expects dates to be in the past unless the `future: true` config entry is included.

Adding `--verbose` I could see:

```
           Reading: _posts/2018-10-31-invoice.markdown
          Skipping: _posts/2018-10-31-invoice.markdown has a future date
```

I think this should be fixed by https://github.com/jdennes/invoices/pull/7 (and you could try just adding `future: true` to your `_config.yml`).

**Comment by SukiCZ** [comment]
Thank you :heart: this solves the issue :godmode:
